# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculate the Gini Index using Rcpp
#'
#' Given a vector of numbers, calcuate the
#' Gini index being sensitive to NAs
#'
#' @param x A numeric vector
#' @return A float of the Gini index where values are
#' between [0,1]
#'
#' @examples
#'
#' x <- runif(1000)
#'
#' @export
giniCpp <- function(x) {
    .Call('_autognet_giniCpp', PACKAGE = 'autognet', x)
}

