# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Run Gibbs sampler for auxiliary covariate values using Rcpp
#'
#' Given the specific inputs, determine auxiliary covariate
#' values using a Gibbs sampling procedure.
#'
#' @param tau A numeric vector for the intercept terms in the covariate model
#' @param rho A numeric vector for the correlation terms in the covariate model
#' @param nu A numberic vector for the neighbor terms in the covariate model
#' @param N An integer indicating the size of the interconnected network
#' @param R An integer indicating the number of iterations for the Gibbs
#' @param J An integer for the number of covariates
#' @param rho_mat A numeric matrix for rho terms
#' @param adjacency A binary matrix indicating connected units
#' @param cov_i A numeric matrix for observed covariate values (starting values for chain)
#' @param weights A numeric vector indicating the number of neighbors for each node
#' @param group_lengths An integer vector indicating the number of categories for each variable
#' @param group_functions An integer vector indicating the type of variable
#' @return A numeric matrix for auxiliary covariate values
#' between [0,1]
#'
#' @examples
#'
#' x <- runif(1000)
#'
#' @export
auxVarCpp <- function(tau, rho, nu, N, R, J, rho_mat, adjacency, cov_i, weights, group_lengths, group_functions) {
    .Call('_autognet_auxVarCpp', PACKAGE = 'autognet', tau, rho, nu, N, R, J, rho_mat, adjacency, cov_i, weights, group_lengths, group_functions)
}

